### ISSUE TITLE
Скрипт не работает корректно

### ISSUE THREAD

**Issue by cakeinpanic** [PsychodelEKS/soap4me-userjs#1]
Галочка появилась, а автопроиграывания не случается

**Comment by PsychodelEKS** [comment]
Хотелось бы подробностей, я сам пользуюсь - работает =)
Какой сериал, галочка то проставлена, серии есть еще, что происходит после окончания текущей серии?
Может ошибки в консоли какие?

**Comment by cakeinpanic** [comment]
Извини, неловко вышло)
Отчаянные домохозяйки, 1 сезон
при любом переставлении ползунка вылезает 10 вот таких ошибок в консоли
```
[.PPAPIContext]GL ERROR :GL_INVALID_ENUM : glTexImage2D: target was GL_TEXTURE_RECTANGLE_ARB
```

по окончании серии ничего нового в консоли нет

**Comment by PsychodelEKS** [comment]
Это ошибка не от моего скрипта.
Попробуй, может, в инкогнито, без других плагинов/скриптов.
Проверил на домохозяйках сейчас - все окей у меня - серия заканчивается и включается следующая.
Смотришь с сабами или в озвучке? Серии не просмотренные (с голубыми точками или без)?

**Comment by cakeinpanic** [comment]
удалила пару плагинов из хрома и заработало ¯\_(ツ)_/¯ 
теперь уже не восстановить, кто из них причинял зло
суперплагин, спасибо, кайфую!

**Comment by PsychodelEKS** [comment]
Лучший вариант решения бага, когда виноват кто-то другой и делать ни чего не пришлось )
